# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'HomeWork9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeWork9
  pod 'Firebase/Auth' 
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  

end
